name = "kashfbot"
main = "index.js"
compatibility_date = "2026-08-01"

[[d1_databases]]
binding = "DB"
database_name = "kashf-db"
database_id = "2befbf3d-1fb5-4e77-906c-6d4770b32543"

[triggers]
crons = ["*/10 * * * *"]